config/routes.rb
Rails.application.routes.draw do
  resources :breeds

  get 'detail/:breed', to: 'breeds#detail', as: 'breed_detail'
  root "breeds#index"

end

app/models/breed.rb
class Breed < ActiveRecord::Base
  validates_presence_of :name, :pic_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breeds_controller.rb
class BreedsController < ApplicationController

  def index
    @list = DogBreedFetcher.list
  end

  def detail
    @breed = DogBreedFetcher.fetch(params[:breed])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breeds_helper.rb
module BreedsHelper
end

app/views/breeds/detail.html.erb
<div class="dog">

  <h1>It's a dog</h1>

  <h3><%= @breed.name.humanize %></h3>

  <%= image_tag @breed.pic_url %>

</div>

app/views/breeds/index.html.erb
<div class="dog">

  <ul class="breed-list">
    <% @list.each do |breed, data| %>
      <li>
        <%= link_to breed, breed_detail_path(breed) %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsTestProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>